/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleadoscrud;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import conexionparadatosempleados.ConexionSQLDatosEmpleados;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paracreacionpool.CargarComboBox;

/**
 *
 * @author josueemilian
 */
public class EditarEmpleadoEliminar extends javax.swing.JFrame {

    //Instancias nuestro objeto conexion
    ConexionSQLDatosEmpleados cc = new ConexionSQLDatosEmpleados();
    Connection con = cc.conexion();

    
     //instanciamos (PARA CARGAR EL COMBOBOX)
    CargarComboBox metodos_CargarComboBox = new CargarComboBox();
    
    
    public EditarEmpleadoEliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarDatos();
        
        //Cargamos nuestro ComboBox con informacion de la DB
        metodos_CargarComboBox.consultarEmpleos(cbPuesto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtCelular = new javax.swing.JTextField();
        txtBusqueda = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        cbPuesto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MANTENIMIENTO EMPLEADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BUSCAR EMPLEADO: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Empleado: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Puesto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Codigo Trabador:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Numero Celular:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 100, 30));
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 300, -1));

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 304, -1));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 300, -1));

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaEmpleados.setShowGrid(true);
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 530, 70));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Elija Empleado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 304, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Apellido Empleado:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel1.add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 304, -1));

        jPanel1.add(cbPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosMouseClicked
        //Evento click el cual me permitira que la a la hora de seleccionar un registro pueda editarlo directamente

        int filaSeleccionada = tablaEmpleados.rowAtPoint(evt.getPoint());

        txtNombre.setText(tablaEmpleados.getValueAt(filaSeleccionada, 1).toString());
        txtEmpleado.setText(tablaEmpleados.getValueAt(filaSeleccionada, 2).toString());
        cbPuesto.setSelectedItem(tablaEmpleados.getValueAt(filaSeleccionada, 3));//Para meterlo en ComboBox
        txtCodigo.setText(tablaEmpleados.getValueAt(filaSeleccionada, 4).toString());
        txtCelular.setText(tablaEmpleados.getValueAt(filaSeleccionada, 5).toString());

    }//GEN-LAST:event_tablaEmpleadosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarDatos();
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarRegistro();
        mostrarDatos();
        limpiarCajas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        filtrarDatos(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyReleased

    public void mostrarDatos() {

        String[] titulos = {"ID", "Nombre", "Apellidos", "Puesto", "Codigo Empleado", "No. celular"}; //estos nombres son los titulos para la tabla de Netbeans
        String[] registros = new String[7];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        //variable consulta todos los datos de la tabla empleado
        String SQL = "select * from empleadodatos"; //este nobmre tiene que ser el que va despues del nombre de la tabla

        //para llenado de la tabla uno por uno
        try {
            Statement st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) { //.next para que me recorra todos los registros de la tabla empleadosumg
                registros[0] = rs.getString("idempleadodatos");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("apellido");
                registros[3] = rs.getString("puesto");
                registros[4] = rs.getString("codigo");
                registros[5] = rs.getString("celular");

                modelo.addRow(registros);

            }
            //mandamos todos los registros a nuestra tabla
            tablaEmpleados.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar Datos: " + e.getMessage());
        }
    }

    //Creamos un metodo para actualizar datos, es similar ha insertar datos, copie y pege el metodo insertarDatos
    public void actualizarDatos() {

        try {
            String SQL = "update empleadodatos set nombre = ?, apellido = ?,puesto = ?,codigo = ?,celular = ? where idempleadodatos = ?"; //modificacion para update

            //conversion a texto de lo que el usuario seleccione
            int filaSeleccionada = tablaEmpleados.getSelectedRow();
            String dao = (String) tablaEmpleados.getValueAt(filaSeleccionada, 0);

            PreparedStatement pst = (PreparedStatement) con.prepareStatement(SQL);

            pst.setString(1, txtNombre.getText());
            pst.setString(2, txtEmpleado.getText());

            //para el combo Box
            int puestoSeleccionado = cbPuesto.getSelectedIndex();            
            pst.setString(3, cbPuesto.getItemAt(puestoSeleccionado));
            
            
            pst.setString(4, txtCodigo.getText());
            pst.setString(5, txtCelular.getText());

            //enviamos la variable dao
            pst.setString(6, dao);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Registro Editado Correctamente!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Edicion " + e.getMessage());
        }

    }

    public void eliminarRegistro() {
        //metodo para eliminar
        int filaSeleccionada = tablaEmpleados.getSelectedRow();

        try {
            String SQL = "delete from empleadodatos where idempleadoDatos = " + tablaEmpleados.getValueAt(filaSeleccionada, 0);

            Statement st = (Statement) con.createStatement();

            int n = st.executeUpdate(SQL);
            if (n >= 0) {
                JOptionPane.showMessageDialog(null, "Registro Eliminado!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar registro: " + e.getMessage());
        }
    }
    
    
    
            //METODO PARA BUSCAR REGISTROS / FILTRAR - EDITANDO PARAMETROS
        public void filtrarDatos(String valor ){ // recibe un parametro que el usuario ingrese a buscar 
       
        String[] titulos = {"ID","Nombre", "Apellidos", "Puesto", "Codigo Empleado", "No. celular"}; //estos nombres son los titulos para la tabla de Netbeans
        String[] registros = new String[7];
        
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        
        //variable consulta todos los datos de la tabla empleado
        String SQL = "select * from empleadodatos where nombre like '%"+valor+"%'"; //este nobmre tiene que ser el que va despues del nombre de la tabla
        
        //para llenado de la tabla uno por uno
        try {
            Statement st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            
          while(rs.next()){ //.next para que me recorra todos los registros de la tabla empleadosumg
              registros[0] = rs.getString("idempleadodatos");
              registros[1] = rs.getString("nombre");
              registros[2] = rs.getString("apellido");
              registros[3] = rs.getString("puesto") ;
              registros[4] = rs.getString("codigo");
              registros[5] = rs.getString("celular");
              
              
              modelo.addRow(registros);
              
          }  
          //mandamos todos los registros a nuestra tabla
          tablaEmpleados.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar Datos: "+e.getMessage());
        }
    }
    

    public void limpiarCajas() {
        //para limpiar las cajas de texto
        txtNombre.setText("");
        txtEmpleado.setText("");
        cbPuesto.setSelectedItem(null);
        txtCodigo.setText("");
        txtCelular.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleadoEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleadoEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleadoEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleadoEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmpleadoEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
