package empleadoscrud;

import java.awt.Color;
import javax.swing.JOptionPane;

public class Programa extends javax.swing.JFrame {

    int xMouse, yMouse;
    public Programa() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondohorizontal = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        horizontalpreuba2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        fondovertical = new javax.swing.JLabel();
        iniciarsesion = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        txtIngresoUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        CONTRASEÑA = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPassword = new javax.swing.JPasswordField();
        ingreso = new javax.swing.JPanel();
        ingresoboton = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        barra = new javax.swing.JPanel();
        studentLogo = new javax.swing.JLabel();

        fondohorizontal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondohorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/horizontalv2.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logov2.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 240, 240));

        horizontalpreuba2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fhoriv2.png"))); // NOI18N
        horizontalpreuba2.setText("jLabel2");
        background.add(horizontalpreuba2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 310, 210));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("UMG NARANJO");
        background.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 310, -1));

        fondovertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verticalof.png"))); // NOI18N
        background.add(fondovertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 310, 530));

        iniciarsesion.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        iniciarsesion.setForeground(new java.awt.Color(0, 0, 0));
        iniciarsesion.setText("INICIAR SESIÓN");
        background.add(iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        usuario.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setText("USUARIO");
        background.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        txtIngresoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtIngresoUsuario.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txtIngresoUsuario.setText("Ingrese su nombre de usuario");
        txtIngresoUsuario.setBorder(null);
        txtIngresoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIngresoUsuarioMousePressed(evt);
            }
        });
        background.add(txtIngresoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 390, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 430, -1));

        CONTRASEÑA.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        CONTRASEÑA.setForeground(new java.awt.Color(0, 0, 0));
        CONTRASEÑA.setText("CONTRASEÑA");
        background.add(CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 430, -1));

        jPassword.setBackground(new java.awt.Color(255, 255, 255));
        jPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jPassword.setText("*****************");
        jPassword.setBorder(null);
        jPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordMousePressed(evt);
            }
        });
        background.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 270, -1));

        ingreso.setBackground(new java.awt.Color(205, 53, 52));
        ingreso.setForeground(new java.awt.Color(255, 255, 255));

        ingresoboton.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        ingresoboton.setForeground(new java.awt.Color(255, 255, 255));
        ingresoboton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresoboton.setText("INGRESAR");
        ingresoboton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresoboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresobotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresobotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresobotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingresoLayout = new javax.swing.GroupLayout(ingreso);
        ingreso.setLayout(ingresoLayout);
        ingresoLayout.setHorizontalGroup(
            ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresoboton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        ingresoLayout.setVerticalGroup(
            ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresoboton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 180, 40));

        exitPanel.setBackground(new java.awt.Color(255, 255, 255));
        exitPanel.setForeground(new java.awt.Color(255, 255, 255));

        exit.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        barra.setBackground(new java.awt.Color(255, 255, 255));
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        background.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 40));

        studentLogo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        studentLogo.setForeground(new java.awt.Color(205, 53, 52));
        studentLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        studentLogo.setText("Admin");
        background.add(studentLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 190, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraMouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exitPanel.setBackground(Color.red);
        exit.setBackground(Color.yellow);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exitPanel.setBackground(Color.white);
        exit.setBackground(Color.black);
    }//GEN-LAST:event_exitMouseExited

    private void ingresobotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresobotonMouseEntered
        ingreso.setBackground(new Color(255, 53, 52));
        ingresoboton.setBackground(Color.black); 
    }//GEN-LAST:event_ingresobotonMouseEntered

    private void ingresobotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresobotonMouseExited
        ingreso.setBackground(new Color(205, 53, 52));
    }//GEN-LAST:event_ingresobotonMouseExited

    private void txtIngresoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIngresoUsuarioMousePressed
        if (txtIngresoUsuario.getText().equals("Ingrese su nombre de usuario")) {
            txtIngresoUsuario.setText("");
            txtIngresoUsuario.setForeground(Color.black);
        }
        
        if (String.valueOf(jPassword.getPassword()).isEmpty()) {
            jPassword.setText("*****************");
            jPassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtIngresoUsuarioMousePressed

    private void jPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMousePressed
        if (String.valueOf(jPassword.getPassword()).equals("*****************")) {
            jPassword.setText("");
            jPassword.setForeground(Color.black);
        }
        
        if (txtIngresoUsuario.getText().isEmpty()) {
            txtIngresoUsuario.setText("Ingrese su nombre de usuario");
            txtIngresoUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordMousePressed

    private void ingresobotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresobotonMouseClicked
        String usuario = "admin", clave = "1234";
        
        String pass = new String (jPassword.getPassword());
        
        if (txtIngresoUsuario.getText().equals(usuario) && pass.equals(clave)) {
            optionIn reutilizar = new optionIn();
            reutilizar.setVisible(true);  
            dispose();

        }else{                   
            JOptionPane.showMessageDialog(this, "usurio / clave incorrecta");
        }
    }//GEN-LAST:event_ingresobotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONTRASEÑA;
    private javax.swing.JPanel background;
    private javax.swing.JPanel barra;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JLabel fondohorizontal;
    private javax.swing.JLabel fondovertical;
    private javax.swing.JLabel horizontalpreuba2;
    private javax.swing.JPanel ingreso;
    public static javax.swing.JLabel ingresoboton;
    private javax.swing.JLabel iniciarsesion;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel name;
    private javax.swing.JLabel studentLogo;
    private javax.swing.JTextField txtIngresoUsuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
